spring.application.name=Challenge LiterAlura

# Dirección de tu base de datos (asegúrate de que el nombre coincida con pgAdmin)
spring.datasource.url=jdbc:postgresql://localhost:5432/literalura_db

# Tu usuario de PostgreSQL (por defecto es postgres)
spring.datasource.username=postgres

# La contraseña que elegiste al instalar PostgreSQL
spring.datasource.password=eliana

# Driver para conectar Java con Postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Esto permite que Hibernate cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false